{% set version = "0.6.0" %}

package:
  name: grequests
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/grequests/grequests-{{ version }}.tar.gz
  sha256: 7dec890c6668e6755a1ea968565535867956639301268394d24df67b478df666

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - gevent
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - grequests

about:
  home: https://github.com/spyoungtech/grequests
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Requests + Gevent'

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
