{% set version = "0.7.0" %}

package:
  name: grequests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grequests/grequests-{{ version }}.tar.gz
  sha256: 5c33f14268df5b8fa1107d8537815be6febbad6ec560524d6a404b7778cf6ba6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - gevent
    - requests

test:
  imports:
    - grequests

about:
  home: https://github.com/spyoungtech/grequests
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Requests + Gevent

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
