{% set version = "0.5.0" %}

package:
  name: grequests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grequests/grequests-{{ version }}.tar.gz
  sha256: 8667198589765447db2a8d39927144207d9e0578d9142ed87ecc0af9ce937e23

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - gevent
    - requests

test:
  imports:
    - grequests

about:
  home: https://github.com/kennethreitz/grequests
  license: BSD 3-Clause
  # license_file: No MANIFEST included in package - see https://github.com/kennethreitz/grequests/issues/95
  license_family: BSD
  summary: Requests + Gevent

extra:
  recipe-maintainers:
    - pmlandwehr
